### PR TITLE
Custom hash algorithms, detect hash collisions

### LINKED ISSUE #21: Hash collision
The example code is not from real application, but anyway

```
var styleSheet = require('free-style').create()
var a = styleSheet.registerStyle({ color: '#0008d0' })
var b = styleSheet.registerStyle({ color: '#000f82' })
console.log(a, b, styleSheet.getStyles())

//=> "f1pqsan1 f1pqsan1 .f1pqsan1{color:#0008d0}"
```

Are there any recommended workarounds? Thanks!

### PR DESCRIPTION
**Pull request by blakeembrey**
* Pass customised hash algorithm around internal class instantiations.
* Implement method to get full identifiers (E.g. CSS style) to detect hash collisions

Closes #21.

Edit: If you're implementing your own hash, you'll need to remember to escape (https://github.com/mathiasbynens/cssesc). Don't really feel the need to take on a 150 line dependency for this feature.

### CODE REVIEW

**Comment by dmitrage** [comment]
Unfortunately, this change doesn't cover all possible collisions :(
Styles with nesting and keyframes are not always catched, because of collision in accumulated hash string.

Gist with failing test cases for the default hash function: https://gist.github.com/dmitrage/1daa3bc5306b176d0df300096441abfb

Keyframes:
Identifier for rules is computed from accumulated hash strings, in my case "fromcolor:#0008datocolor:red" and "fromcolor:#000f8ctocolor:red". Default hash function produces same hash value for both: "uybv9". So rules are constructed with `rule` = `"@keyframes huybv9"` and `styles` = `""`. `getIdentifier` returns same value, collision not detected.

**Comment by blakeembrey** [comment]
Great catch, I'm not handling any accumulated hash strings in the detection. Not sure of the best way to do that right now, but I'll think on it.

**Comment by dmitrage** [comment]
The simplest thing I've found is to add `hashString` property to `Selector` and `Rule` and use it in `getIdentifier`. Not sure if it is 100% correct but at least all tests are passing. I've forked this branch and created a [commit](https://github.com/dmitrage/free-style/commit/fbcebf54a69014687ab7c8c27c990ff1f9bae6b8) on top to show the idea.

**Comment by blakeembrey** [comment]
Thanks for the idea, I was hoping not to have to keep around the extra data but it makes sense that I may have to (though the identifier diff is probably going to be a lot more confusing). I'll review and try to get that into the PR for the next release 👍

**Pull request merged**
